version: "3"
services:
  backend:
    build:
      context: ./backend
    restart: always
    network_mode: "host"
    ports:
      - "5000:5000"


  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "3036:3000"
    depends_on:
      - backend

